import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionProvider from "@/components/SessionProvider";
import { UiCtxProvider } from "@/context/UiContext";
import AccountMenu from "@/components/AccountMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Google Jocs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SessionProvider>
        <UiCtxProvider>
          <body className={inter.className}>
            <AccountMenu />
            {children}
          </body>
        </UiCtxProvider>
      </SessionProvider>
    </html>
  );
}
